POST http://localhost:8000/users HTTP/1.1
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@doe.com",
  "password": "a_vida_e_bela"
}

###

POST http://localhost:8000/users/generate_token HTTP/1.1
Content-Type: application/json

{
  "email": "john@doe.com",
  "password": "a_vida_e_bela"
}